schema_version: 1

context:
  python_min: "3.11"
  version: "2026.5.1"

package:
  name: jax-galsim
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jax-galsim/jax_galsim-${{ version }}.tar.gz
  sha256: f28411a967f85539b37a98421059c749cec4ac5fa3b526895797060404e37713

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=45
    - setuptools-scm >=8
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=1.18.0
    - galsim >=2.7.0
    - jax >=0.6.0
    - astropy-base >=2.0
    - quadax

tests:
  - python:
      imports:
        - jax_galsim
      # fails due to galsim
      pip_check: false
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: The modular galaxy image simulation toolkit, but in JAX
  license: BSD-2-Clause AND Apache-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/JAX-GalSim/
  documentation: https://jax-galsim.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - beckermr
